export const lifeStudyTopicsCatalog = [
  {
    id: 'housing-support-2026',
    icon: '🏡',
    category: '금융 상식',
    badge: '정책 총정리',
    readTime: '5분',
    updatedAt: '2026 기준',
    title: '청년·신혼부부를 위한 2026 주거지원 정책',
    subtitle: '주거비용 지원 4가지 · 공공임대 5가지',
    summary: '주거안정장학금부터 청년월세지원, 전세보증금 반환보증 보증료 지원, 행복주택과 통합공공임대까지 교재 기준 핵심 정책을 한눈에 정리했습니다.',
  },
  {
    id: 'youth-policy-2026',
    icon: '🎓',
    category: '금융 상식',
    badge: '청년 지원 6선',
    readTime: '5분',
    updatedAt: '2026 기준',
    title: '대학생·취업준비생이 꼭 챙겨야 할 2026 청년정책',
    subtitle: '장학금 · 저금리대출 · 일경험 · 창업',
    summary: '국가장학금, 햇살론유스, K-Move 스쿨, 청년창업사관학교, 미래내일일경험, 국가기술자격 응시료 지원까지 교재의 6개 정책을 단원으로 묶었습니다.',
  },
  {
    id: 'year-end-tax-settlement-2026',
    icon: '🧾',
    category: '금융 상식',
    badge: '오답노트',
    readTime: '4분',
    updatedAt: '2026 시즌',
    title: '연말정산 오답노트',
    subtitle: '부양가족 · 월세 · 대출 · 의료비',
    summary: '국세청 오답노트를 바탕으로 과다공제가 자주 생기는 4개 항목을 정리했습니다. 조건을 놓쳐 가산세로 이어지지 않도록 체크포인트 중심으로 구성했습니다.',
  },
  {
    id: 'iran-war-oil',
    icon: '🛢️',
    category: '세계 이슈',
    badge: '지금 보는 이슈',
    readTime: '3분',
    updatedAt: '2026-04',
    title: '이란 전쟁과 석유',
    subtitle: '호르무즈 해협 · 유가 · 환율 영향',
    summary: '중동 충돌이 왜 국제유가, 물가, 환율 이야기로 바로 이어지는지 핵심 연결고리만 빠르게 설명합니다.',
    coverImage: '/cardnews/iran-war-oil/1.png',
    cardNews: [
      { src: '/cardnews/iran-war-oil/1.png' },
      { src: '/cardnews/iran-war-oil/2.png' },
      { src: '/cardnews/iran-war-oil/3.png' },
      { src: '/cardnews/iran-war-oil/4.png' },
      { src: '/cardnews/iran-war-oil/5.png' },
    ],
  },
];
