export const teenQuizUnitsCatalog = [
  {
    id: 'teen-unit1',
    icon: '🤝',
    title: '난 함께 쓴다!',
    subtitle: '재화와 서비스의 효과적 관리',
    studyTopicId: 'teen-shared-spending',
    quizzes: [
      { id: 'teen-unit1-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 50 },
      { id: 'teen-unit1-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 50 },
      { id: 'teen-unit1-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 50 },
    ],
  },
  {
    id: 'teen-unit2',
    icon: '🧠',
    title: '스마트 소비, 세상을 바꾸다!',
    subtitle: '합리적 소비',
    studyTopicId: 'teen-smart-consumption',
    quizzes: [
      { id: 'teen-unit2-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 50 },
      { id: 'teen-unit2-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 50 },
      { id: 'teen-unit2-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 50 },
    ],
  },
  {
    id: 'teen-unit3',
    icon: '💳',
    title: '체크카드 체크하기!',
    subtitle: '다양한 지불수단과 효과적인 체크카드 사용 방법에 대한 이해',
    studyTopicId: 'teen-check-card',
    quizzes: [
      { id: 'teen-unit3-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 50 },
      { id: 'teen-unit3-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 50 },
      { id: 'teen-unit3-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 50 },
    ],
  },
  {
    id: 'teen-unit4',
    icon: '🛍️',
    title: '전자상거래 사용 설명서',
    subtitle: '전자상거래 사용에 유의하는 태도',
    studyTopicId: 'teen-ecommerce',
    quizzes: [
      { id: 'teen-unit4-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 50 },
      { id: 'teen-unit4-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 50 },
      { id: 'teen-unit4-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 50 },
    ],
  },
  {
    id: 'teen-unit5',
    icon: '📒',
    title: '나만의 용돈 관리법',
    subtitle: '용돈 관리',
    studyTopicId: 'teen-allowance',
    quizzes: [
      { id: 'teen-unit5-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 60 },
      { id: 'teen-unit5-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 60 },
      { id: 'teen-unit5-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 60 },
    ],
  },
  {
    id: 'teen-unit6',
    icon: '💼',
    title: '소득을 관리해 드립니다!',
    subtitle: '아르바이트 등을 통해 번 소득의 관리',
    studyTopicId: 'teen-income-management',
    quizzes: [
      { id: 'teen-unit6-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 60 },
      { id: 'teen-unit6-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 60 },
      { id: 'teen-unit6-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 60 },
    ],
  },
  {
    id: 'teen-unit7',
    icon: '🏦',
    title: '슬기로운 예금 생활',
    subtitle: '금융상품에 대한 이해와 활용',
    studyTopicId: 'teen-savings',
    quizzes: [
      { id: 'teen-unit7-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 60 },
      { id: 'teen-unit7-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 60 },
      { id: 'teen-unit7-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 60 },
    ],
  },
  {
    id: 'teen-unit8',
    icon: '🧾',
    title: '신용, 너 사용법',
    subtitle: '부채와 신용의 관리',
    studyTopicId: 'teen-credit-debt',
    quizzes: [
      { id: 'teen-unit8-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 60 },
      { id: 'teen-unit8-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 60 },
      { id: 'teen-unit8-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 60 },
    ],
  },
  {
    id: 'teen-unit9',
    icon: '🛠️',
    title: '내 노동의 의미',
    subtitle: '노동의 중요성과 가치에 대한 이해',
    studyTopicId: 'teen-value-of-work',
    quizzes: [
      { id: 'teen-unit9-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 70 },
      { id: 'teen-unit9-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 70 },
      { id: 'teen-unit9-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 70 },
    ],
  },
  {
    id: 'teen-unit10',
    icon: '🧭',
    title: '꿈스타그램',
    subtitle: '건설적인 진로 설계',
    studyTopicId: 'teen-career-design',
    quizzes: [
      { id: 'teen-unit10-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 70 },
      { id: 'teen-unit10-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 70 },
      { id: 'teen-unit10-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 70 },
    ],
  },
  {
    id: 'teen-unit11',
    icon: '⚖️',
    title: '10대의 노동 이야기',
    subtitle: '노동권에 대한 이해와 침해 시 대처',
    studyTopicId: 'teen-labor-rights',
    quizzes: [
      { id: 'teen-unit11-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 70 },
      { id: 'teen-unit11-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 70 },
      { id: 'teen-unit11-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 70 },
    ],
  },
  {
    id: 'teen-unit12',
    icon: '🚫',
    title: '인생까지 베팅하겠습니까?',
    subtitle: '도박이나 사행성게임에 대한 주의',
    studyTopicId: 'teen-gambling-prevention',
    quizzes: [
      { id: 'teen-unit12-quiz1', title: '퀴즈 1', subtitle: '핵심 개념 이해', xpReward: 70 },
      { id: 'teen-unit12-quiz2', title: '퀴즈 2', subtitle: '상황별 판단', xpReward: 70 },
      { id: 'teen-unit12-quiz3', title: '퀴즈 3', subtitle: '실전 적용', xpReward: 70 },
    ],
  },
];
