export const teenQuizUnitsCatalog = [
  {
    id: 'teen-unit1',
    icon: '🤝',
    title: '난 함께 쓴다!',
    titleEn: 'We Use Together!',
    subtitle: '공유 자원과 책임 있는 사용',
    subtitleEn: 'Shared Resources and Responsible Usage',
    studyTopicId: 'teen-shared-spending',
    quizzes: [
      { id: 'teen-unit1-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '공유지의 비극', subtitleEn: 'The Tragedy of the Commons', xpReward: 50 },
      { id: 'teen-unit1-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '공용 자원이란 무엇인가?', subtitleEn: 'What Are Public Resources?', xpReward: 50 },
      { id: 'teen-unit1-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '공용 자원 사용의 문제점 분석', subtitleEn: 'Analyzing Problems in the Use of Public Resources', xpReward: 50 },
      { id: 'teen-unit1-quiz4', title: '퀴즈 4', titleEn: 'Quiz 4', subtitle: '공용 자원의 효과적 사용 방안', subtitleEn: 'Effective Ways to Use Public Resources', xpReward: 50 },
    ],
  },
  {
    id: 'teen-unit2',
    icon: '🧠',
    title: '스마트 소비, 세상을 바꾸다!',
    titleEn: 'Smart Spending Changes the World!',
    subtitle: '합리적 소비',
    subtitleEn: 'Rational Consumption',
    studyTopicId: 'teen-smart-consumption',
    quizzes: [
      { id: 'teen-unit2-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '자원의 희소성', subtitleEn: 'Scarcity of Resources', xpReward: 50 },
      { id: 'teen-unit2-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '합리적 선택', subtitleEn: 'Rational Choices', xpReward: 50 },
      { id: 'teen-unit2-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '비합리적 소비', subtitleEn: 'Irrational Consumption', xpReward: 50 },
    ],
  },
  {
    id: 'teen-unit3',
    icon: '💳',
    title: '체크카드 체크하기!',
    titleEn: 'Check Your Check Card!',
    subtitle: '다양한 지불수단과 효과적인 체크카드 사용 방법에 대한 이해',
    subtitleEn: 'Understanding Different Payment Methods and Effective Debit Card Usage',
    studyTopicId: 'teen-check-card',
    quizzes: [
      { id: 'teen-unit3-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '지불수단의 종류와 특징', subtitleEn: 'Types and Features of Payment Methods', xpReward: 50 },
      { id: 'teen-unit3-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '체크카드의 효과적 사용', subtitleEn: 'Effective Use of Debit Cards', xpReward: 50 },
    ],
  },
  {
    id: 'teen-unit4',
    icon: '🛍️',
    title: '전자상거래 사용 설명서',
    titleEn: 'Guide to E-Commerce',
    subtitle: '전자상거래 사용에 유의하는 태도',
    subtitleEn: 'Being Careful When Using E-Commerce',
    studyTopicId: 'teen-ecommerce',
    quizzes: [
      { id: 'teen-unit4-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '유형·위험', subtitleEn: 'Types and Risks', xpReward: 50 },
      { id: 'teen-unit4-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '피해·환불 기준', subtitleEn: 'Damage Compensation and Refund Standards', xpReward: 50 },
      { id: 'teen-unit4-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '예방·대응 원칙', subtitleEn: 'Prevention and Response Principles', xpReward: 50 },
    ],
  },
  {
    id: 'teen-unit5',
    icon: '📒',
    title: '나만의 용돈 관리법',
    titleEn: 'My Allowance Management Plan',
    subtitle: '용돈 관리',
    subtitleEn: 'Allowance Management',
    studyTopicId: 'teen-allowance',
    quizzes: [
      { id: 'teen-unit5-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '수입·지출·저축 구조', subtitleEn: 'Income, Spending, and Savings Structure', xpReward: 60 },
      { id: 'teen-unit5-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '기록·목표 설정', subtitleEn: 'Record Keeping and Goal Setting', xpReward: 60 },
      { id: 'teen-unit5-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '실행·점검', subtitleEn: 'Execution and Review', xpReward: 60 },
    ],
  },
  {
    id: 'teen-unit6',
    icon: '💼',
    title: '소득을 관리해 드립니다!',
    titleEn: 'Managing Your Income!',
    subtitle: '아르바이트 등을 통해 번 소득의 관리',
    subtitleEn: 'Managing Income Earned Through Part-Time Jobs and More',
    studyTopicId: 'teen-income-management',
    quizzes: [
      { id: 'teen-unit6-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '소득 종류·구분', subtitleEn: 'Types and Classification of Income', xpReward: 60 },
      { id: 'teen-unit6-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '정기/비정기와 계획', subtitleEn: 'Regular vs. Irregular Income and Planning', xpReward: 60 },
      { id: 'teen-unit6-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '분배·통장 분리', subtitleEn: 'Income Allocation and Separate Bank Accounts', xpReward: 60 },
    ],
  },
  {
    id: 'teen-unit7',
    icon: '🏦',
    title: '슬기로운 예금 생활',
    titleEn: 'Smart Saving Habits',
    subtitle: '금융상품에 대한 이해와 활용',
    subtitleEn: 'Understanding and Using Financial Products',
    studyTopicId: 'teen-savings',
    quizzes: [
      { id: 'teen-unit7-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '은행 역할·예금상품', subtitleEn: 'The Role of Banks and Deposit Products', xpReward: 60 },
      { id: 'teen-unit7-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '단리·복리', subtitleEn: 'Simple Interest and Compound Interest', xpReward: 60 },
      { id: 'teen-unit7-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '안정성·예금자보호', subtitleEn: 'Stability and Deposit Protection', xpReward: 60 },
    ],
  },
  {
    id: 'teen-unit8',
    icon: '🧾',
    title: '신용, 너 사용법',
    titleEn: 'How to Use Credit Wisely',
    subtitle: '부채와 신용의 관리',
    subtitleEn: 'Managing Debt and Credit',
    studyTopicId: 'teen-credit-debt',
    quizzes: [
      { id: 'teen-unit8-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '신용·신용점수 기초', subtitleEn: 'Basics of Credit and Credit Scores', xpReward: 60 },
      { id: 'teen-unit8-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '점수 영향 요소·오해', subtitleEn: 'Factors Affecting Credit Scores and Common Misunderstandings', xpReward: 60 },
      { id: 'teen-unit8-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '신용관리 실천', subtitleEn: 'Practicing Good Credit Management', xpReward: 60 },
    ],
  },
  {
    id: 'teen-unit9',
    icon: '🛠️',
    title: '내 노동의 의미',
    titleEn: 'The Meaning of My Work',
    subtitle: '노동의 중요성과 가치에 대한 이해',
    subtitleEn: 'Understanding the Importance and Value of Labor',
    studyTopicId: 'teen-value-of-work',
    quizzes: [
      { id: 'teen-unit9-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '노동 vs 근로·개인 가치', subtitleEn: 'Labor vs. Work and Personal Value', xpReward: 70 },
      { id: 'teen-unit9-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '국가 가치·노동생산성', subtitleEn: 'National Value and Labor Productivity', xpReward: 70 },
      { id: 'teen-unit9-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '통계·주요용어', subtitleEn: 'Statistics and Key Terms', xpReward: 70 },
    ],
  },
  {
    id: 'teen-unit10',
    icon: '🧭',
    title: '꿈스타그램',
    titleEn: 'Dreamstagram',
    subtitle: '건설적인 진로 설계',
    subtitleEn: 'Constructive Career Planning',
    studyTopicId: 'teen-career-design',
    quizzes: [
      { id: 'teen-unit10-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '자기이해·직업탐색', subtitleEn: 'Self-Understanding and Career Exploration', xpReward: 70 },
      { id: 'teen-unit10-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '비전·R=VD', subtitleEn: 'Vision and R=VD', xpReward: 70 },
      { id: 'teen-unit10-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '로드맵·피드백 실천', subtitleEn: 'Roadmaps and Putting Feedback into Action', xpReward: 70 },
    ],
  },
  {
    id: 'teen-unit11',
    icon: '⚖️',
    title: '10대의 노동 이야기',
    titleEn: 'Teen Labor Stories',
    subtitle: '노동권에 대한 이해와 침해 시 대처',
    subtitleEn: 'Understanding Labor Rights and Responding to Violations',
    studyTopicId: 'teen-labor-rights',
    quizzes: [
      { id: 'teen-unit11-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '근로계약·근로시간', subtitleEn: 'Work Contracts and Working Hours', xpReward: 70 },
      { id: 'teen-unit11-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '임금·휴게·주휴수당', subtitleEn: 'Wages, Breaks, and Weekly Holiday Pay', xpReward: 70 },
      { id: 'teen-unit11-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '권리침해 대응', subtitleEn: 'Responding to Rights Violations', xpReward: 70 },
    ],
  },
  {
    id: 'teen-unit12',
    icon: '🚫',
    title: '인생까지 베팅하겠습니까?',
    titleEn: 'Would You Bet Your Life Too?',
    subtitle: '도박이나 사행성게임에 대한 주의',
    subtitleEn: 'Awareness of Gambling and Speculative Games',
    studyTopicId: 'teen-gambling-prevention',
    quizzes: [
      { id: 'teen-unit12-quiz1', title: '퀴즈 1', titleEn: 'Quiz 1', subtitle: '정의·위험·유인 구조', subtitleEn: 'Definitions, Risks, and Reward Structures', xpReward: 70 },
      { id: 'teen-unit12-quiz2', title: '퀴즈 2', titleEn: 'Quiz 2', subtitle: '2차 범죄·피해', subtitleEn: 'Secondary Crimes and Harm', xpReward: 70 },
      { id: 'teen-unit12-quiz3', title: '퀴즈 3', titleEn: 'Quiz 3', subtitle: '예방·상담·도움요청', subtitleEn: 'Prevention, Counseling, and Asking for Help', xpReward: 70 },
    ],
  },
];
